### ISSUE TITLE
Ancient previous attempt by someone

### ISSUE THREAD

**Issue by Python1320** [RaphaelIT7/gmod-lua-shared#1]
In case it helps: 
 - https://github.com/meepen/gluajit
 - https://github.com/Cynosphere/gbins/tree/master/gmod_luajit/src

Can't even find the thread from google anymore...

**Comment by RaphaelIT7** [comment]
I've looked at both projects, but sadly none of them seem to actually recreate the classes
But gluajit showed how lua_init_stack_gmod was implemented, so that's definitely going to be useful.

Thanks for showing me these projects :D

**Comment by RaphaelIT7** [comment]
I think this can now be closed
